from typing import Dict, Any
from app.chat.intent.interfaces import IIntentService
from app.chat.intent.models.analysis_result import IntentAnalysisResult
from app.chat.intent.pipeline.context import IntentPipelineContext
from app.chat.intent.pipeline.orchestrator import IntentOrchestrator

class IntentIntelligenceService(IIntentService):
    def __init__(self, orchestrator: IntentOrchestrator):
        self._orchestrator = orchestrator

    async def analyze_intent(self, query: str, conversation_context: Dict[str, Any]) -> IntentAnalysisResult:
        # Initialize pipeline context
        context = IntentPipelineContext(
            query=query,
            conversation_context=conversation_context
        )
        
        # Execute the intent intelligence pipeline
        final_context = await self._orchestrator.execute_pipeline(context)
        
        # Map back to DTO
        primary = final_context.candidate_intents[0] if final_context.candidate_intents else None
        secondary = final_context.candidate_intents[1:] if len(final_context.candidate_intents) > 1 else []
        
        # In case the fallback/policy bypassed primary creation (failsafe)
        if not primary:
            from app.chat.intent.models.analysis_result import DetectedIntent
            from app.chat.intent.models.intent_types import IntentType
            primary = DetectedIntent(
                type=IntentType.UNKNOWN,
                confidence=0.0,
                reason="No intent was generated by the pipeline"
            )
            
        return IntentAnalysisResult(
            primary_intent=primary,
            secondary_intents=secondary,
            entities=final_context.entities,
            conversation_context=final_context.conversation_context,
            clarification_request=final_context.clarification_request,
            route_recommendation=final_context.route_recommendation,
            execution_recommendation=final_context.execution_recommendation
        )
