# Generated by Django 6.0.7 on 2026-08-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_cert_user_slug_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course_slug',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
