from enum import Enum

class Capability(str, Enum):
    LOG_ANALYSIS = "LOG_ANALYSIS"
    IOC_ENRICHMENT = "IOC_ENRICHMENT"
    THREAT_ACTOR_LOOKUP = "THREAT_ACTOR_LOOKUP"
    MITRE_MAPPING = "MITRE_MAPPING"
    INCIDENT_TIMELINE = "INCIDENT_TIMELINE"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"
    CONCEPT_EXPLANATION = "CONCEPT_EXPLANATION"
    LAB_GUIDANCE = "LAB_GUIDANCE"
    ASSESSMENT_REVIEW = "ASSESSMENT_REVIEW"
    LEARNING_RECOMMENDATION = "LEARNING_RECOMMENDATION"
    INVESTIGATION = "INVESTIGATION"
    REPORTING = "REPORTING"
    THREAT_INTEL = "THREAT_INTEL"
