from abc import ABC, abstractmethod
from app.tools.models.tool_request import ToolRequest
from app.tools.models.tool_response import ToolResponse

class IToolService(ABC):
    """
    Contract for the Tool Service orchestrator.
    
    Responsibilities:
        - Manage the entire lifecycle of a tool invocation.
        - Orchestrate Enterprise Guardrails (pre/post execution).
        - Orchestrate Cache lookups and storage.
        
    Must Do:
        - Delegate execution to IToolExecutor if validations pass.
        - Return ToolResponse generated by cache, guardrails, or executor.
        
    Must Never Do:
        - Never execute tools directly.
        - Never handle low-level HTTP client mechanics.
        
    Architecture Invariants:
        1. Chat API MUST communicate only with IToolService.
        2. ToolService MUST NEVER execute tools directly.
        3. All external communication MUST go through Infrastructure (not Service).
    """
    
    @abstractmethod
    async def handle_tool_call(self, request: ToolRequest) -> ToolResponse:
        """
        Orchestrates the complete lifecycle of a tool call (Pre-execution, Execution, Post-execution).
        
        Args:
            request (ToolRequest): The execution request.
            
        Returns:
            ToolResponse: The final sanitized response to be returned to the Chat API.
        """
        pass
